apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: kubefim
  namespace: kubefim-system
  labels:
    app.kubernetes.io/name: kubefim
    app.kubernetes.io/part-of: owasp-kubefim
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: kubefim
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: kubefim
        app.kubernetes.io/part-of: owasp-kubefim
    spec:
      serviceAccountName: kubefim
      automountServiceAccountToken: true
      hostPID: true
      nodeSelector:
        kubernetes.io/os: linux
      tolerations:
        - operator: Exists
      terminationGracePeriodSeconds: 10
      initContainers:
        - name: prepare-node
          image: abhijitowasp/owasp-kubefim:init-v0.1.0-alpha.1
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: true
            allowPrivilegeEscalation: true
          volumeMounts:
            - name: host-sys
              mountPath: /host/sys
              mountPropagation: Bidirectional
      containers:
        - name: kubefim
          image: abhijitowasp/owasp-kubefim:v0.1.0-alpha.1
          imagePullPolicy: IfNotPresent
          args:
            - --output=json
            - --config=/etc/kubefim/policy.yaml
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          securityContext:
            privileged: true
            allowPrivilegeEscalation: true
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 500m
              memory: 256Mi
          volumeMounts:
            - name: policy
              mountPath: /etc/kubefim
              readOnly: true
            - name: tracefs
              mountPath: /sys/kernel/tracing
              readOnly: true
            - name: host-proc
              mountPath: /host/proc
              readOnly: true
      volumes:
        - name: policy
          configMap:
            name: kubefim-policy
        - name: tracefs
          hostPath:
            path: /sys/kernel/tracing
            type: Directory
        - name: host-sys
          hostPath:
            path: /sys
            type: Directory
        - name: host-proc
          hostPath:
            path: /proc
            type: Directory
