apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubefim
  namespace: kubefim-system
  labels:
    app.kubernetes.io/name: kubefim
    app.kubernetes.io/part-of: owasp-kubefim
automountServiceAccountToken: true
