// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm

package bpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type BpfEventT struct {
	_               structs.HostLayout
	TimestampNs     uint64
	CgroupId        uint64
	ReturnValue     int64
	SchemaVersion   uint32
	EventType       uint32
	Pid             uint32
	Tgid            uint32
	Ppid            uint32
	Uid             uint32
	Gid             uint32
	MntNsId         uint32
	PidNsId         uint32
	Comm            [16]int8
	Path            [256]int8
	DestinationPath [256]int8
	Reserved        uint32
}

// LoadBpf returns the embedded CollectionSpec for Bpf.
func LoadBpf() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_BpfBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load Bpf: %w", err)
	}

	return spec, err
}

// LoadBpfObjects loads Bpf and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*BpfObjects
//	*BpfPrograms
//	*BpfMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadBpfObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadBpf()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// BpfSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type BpfSpecs struct {
	BpfProgramSpecs
	BpfMapSpecs
	BpfVariableSpecs
}

// BpfProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type BpfProgramSpecs struct {
	TpEnterChmod     *ebpf.ProgramSpec `ebpf:"tp_enter_chmod"`
	TpEnterFchmodat  *ebpf.ProgramSpec `ebpf:"tp_enter_fchmodat"`
	TpEnterFchmodat2 *ebpf.ProgramSpec `ebpf:"tp_enter_fchmodat2"`
	TpEnterOpenat    *ebpf.ProgramSpec `ebpf:"tp_enter_openat"`
	TpEnterRenameat2 *ebpf.ProgramSpec `ebpf:"tp_enter_renameat2"`
	TpEnterUnlinkat  *ebpf.ProgramSpec `ebpf:"tp_enter_unlinkat"`
	TpExitChmod      *ebpf.ProgramSpec `ebpf:"tp_exit_chmod"`
	TpExitFchmodat   *ebpf.ProgramSpec `ebpf:"tp_exit_fchmodat"`
	TpExitFchmodat2  *ebpf.ProgramSpec `ebpf:"tp_exit_fchmodat2"`
	TpExitOpenat     *ebpf.ProgramSpec `ebpf:"tp_exit_openat"`
	TpExitRenameat2  *ebpf.ProgramSpec `ebpf:"tp_exit_renameat2"`
	TpExitUnlinkat   *ebpf.ProgramSpec `ebpf:"tp_exit_unlinkat"`
}

// BpfMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type BpfMapSpecs struct {
	Events        *ebpf.MapSpec `ebpf:"events"`
	PendingEvents *ebpf.MapSpec `ebpf:"pending_events"`
	ScratchEvent  *ebpf.MapSpec `ebpf:"scratch_event"`
}

// BpfVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type BpfVariableSpecs struct {
}

// BpfObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type BpfObjects struct {
	BpfPrograms
	BpfMaps
	BpfVariables
}

func (o *BpfObjects) Close() error {
	return _BpfClose(
		&o.BpfPrograms,
		&o.BpfMaps,
	)
}

// BpfMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type BpfMaps struct {
	Events        *ebpf.Map `ebpf:"events"`
	PendingEvents *ebpf.Map `ebpf:"pending_events"`
	ScratchEvent  *ebpf.Map `ebpf:"scratch_event"`
}

func (m *BpfMaps) Close() error {
	return _BpfClose(
		m.Events,
		m.PendingEvents,
		m.ScratchEvent,
	)
}

// BpfVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to LoadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type BpfVariables struct {
}

// BpfPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type BpfPrograms struct {
	TpEnterChmod     *ebpf.Program `ebpf:"tp_enter_chmod"`
	TpEnterFchmodat  *ebpf.Program `ebpf:"tp_enter_fchmodat"`
	TpEnterFchmodat2 *ebpf.Program `ebpf:"tp_enter_fchmodat2"`
	TpEnterOpenat    *ebpf.Program `ebpf:"tp_enter_openat"`
	TpEnterRenameat2 *ebpf.Program `ebpf:"tp_enter_renameat2"`
	TpEnterUnlinkat  *ebpf.Program `ebpf:"tp_enter_unlinkat"`
	TpExitChmod      *ebpf.Program `ebpf:"tp_exit_chmod"`
	TpExitFchmodat   *ebpf.Program `ebpf:"tp_exit_fchmodat"`
	TpExitFchmodat2  *ebpf.Program `ebpf:"tp_exit_fchmodat2"`
	TpExitOpenat     *ebpf.Program `ebpf:"tp_exit_openat"`
	TpExitRenameat2  *ebpf.Program `ebpf:"tp_exit_renameat2"`
	TpExitUnlinkat   *ebpf.Program `ebpf:"tp_exit_unlinkat"`
}

func (p *BpfPrograms) Close() error {
	return _BpfClose(
		p.TpEnterChmod,
		p.TpEnterFchmodat,
		p.TpEnterFchmodat2,
		p.TpEnterOpenat,
		p.TpEnterRenameat2,
		p.TpEnterUnlinkat,
		p.TpExitChmod,
		p.TpExitFchmodat,
		p.TpExitFchmodat2,
		p.TpExitOpenat,
		p.TpExitRenameat2,
		p.TpExitUnlinkat,
	)
}

func _BpfClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed bpf_bpfel.o
var _BpfBytes []byte
